### ISSUE TITLE
Fails to build DEA on this new update.

### ISSUE THREAD

**Issue by ronnie123442** [RealBlazeIt/DEA#27]
https://pastebin.com/VBTL4Pte

**Comment by RealBlazeIt** [comment]
I don't have the discord.net nightly build feed added in a nuget.config yet, will keep this issue open until thats done, then you won't get those errors.

**Comment by ronnie123442** [comment]
What's the ETA on this fix?

**Comment by RealBlazeIt** [comment]
fixed

**Comment by ronnie123442** [comment]
@RealBlazeIt It still fails to build on this current update

**Comment by RealBlazeIt** [comment]
Could you provide the build failure info

**Comment by ronnie123442** [comment]
https://pastebin.com/yB3GkifE

**Comment by ronnie123442** [comment]
Any Progress on this?

**Comment by RealBlazeIt** [comment]
sorry for this taking so long, it should work perfectly now.

**Comment by ronnie123442** [comment]
just curious what is your discord
