### ISSUE TITLE
Credentials Example

### ISSUE THREAD

**Issue by FozzieDaFox** [RealBlazeIt/dea#29]
I was wondering if there is a credentials example.json file, I can't seem to find it,

Thanks,

**Comment by RealBlazeIt** [comment]
I will rework the README file tomorrow explaining how to selfhost, but for now, here is the format:
```json
{
  "token": "enter token here",
  "mongodbConnectionUrl": "mongodb://dbuser:dbpassword@URL/databaseName"
}
```

**Comment by FozzieDaFox** [comment]
Thank you!

**Comment by RealBlazeIt** [comment]
The README.md has been updated with all information related to self hosting at the bottom.
