### ISSUE TITLE
Erorr Starting

### ISSUE THREAD

**Issue by malekksa505** [RealBlazeIt/dea#35]
C:\Users\*****\Desktop\dea-master>node src/index.js
(node:5416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): MongoError: failed to connect to server [ConnectionURL:27017] on fi
rst connect [MongoError: getaddrinfo ENOTFOUND ConnectionURL ConnectionURL:27017
]
(node:5416) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by RealBlazeIt** [comment]
The error explains itself, your mongodb connection string is incorrect.

**Comment by malekksa505** [comment]
How is that ! is there a solution to that?

@RealBlazeIt

**Comment by RealBlazeIt** [comment]
This git isn't a support thread for selfhosters, it's simply for the open source of DEA. If you can't figure it out on your own, you shouldn't be hosting.

**Comment by malekksa505** [comment]
ok thank u

you have skype please or discord server 
so i can talk to you
