### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by InternalCosmos** [RealBlazeIt/dea#40]
I had this issue after attempting to start the bot up.
```/home/ubuntu/workspace/dea/src/index.js:26
async function initiate() {
      ^^^^^^^^

SyntaxError: Unexpected token function

**Comment by Assley** [comment]
That error occurs because default async/await is not supported in Node.js versions that is less than 7.6.
You can either enable the harmony flag or simply download Node.js version 7.6 or above (8.7 is the latest version of as now). The 2nd option is recommended as its much simpler than the first.

**Comment by RealBlazeIt** [comment]
What @Assley said, and discord.js literally requires node 8.0 or higher, so you need to upgrade.
